### ISSUE TITLE
Accessibility check is invalid when alert or prompt box is found

### ISSUE THREAD

**Issue by kaviarasan96** [sridharbandi/Java-a11y#11]
When an alert or prompt box is in front of page it returns the results as 0.

**Comment by sridharbandi** [comment]
@kaviarasan96 Can you provide me with the URL you are using? I will look at it and revert back to you.

**Comment by kaviarasan96** [comment]
https://www.tutorialsteacher.com/codeeditor?cid=js-1

**Comment by sridharbandi** [comment]
@kaviarasan96  You need to run the accessibility tests after closing the popup or alert box.
