### ISSUE TITLE
Webdriver wait used in A11Y class is not supported in selenium 4

### ISSUE THREAD

**Issue by christinajoice-s** [sridharbandi/Java-a11y#18]
In selenium 4, the existing wait method "WebDriverWait wait = new WebDriverWait(driver, 30);" is not supported. So please make changes accordingly.

![Screenshot from 2022-09-23 13-22-02](https://user-images.githubusercontent.com/53044385/191914909-99a281a9-fb2a-40b4-8040-45bc892a6578.png)

![Screenshot from 2022-09-23 13-20-34](https://user-images.githubusercontent.com/53044385/191914771-35cd9549-1c51-411f-986c-2c74ff7fb03e.png)

**Comment by sridharbandi** [comment]
I will fix it and publish the new version soon.

**Comment by sridharbandi** [comment]
Hi @christinajoice-s, this issue is been now fixed in version 3.0.1
