### ISSUE TITLE
Utils for getting errors, warnings, notices count

### ISSUE THREAD

**Issue by akramshuja** [sridharbandi/Java-a11y#23]
Hi Sridhar,
We already had a test suite running on your 2.0 alpha 2 release. We decided to upgrade it to the latest 3.01, but we noticed that the below is no longer supported:
1. Getting the count of all issues. We used to take various decisions based on these counts.
2. Providing a page name manually on which tests are executed. From what I understand, it always picks up from the title of the page now. The way our application works is different, we have multiple iframes in the background, but only one of them is rendered at once. And each of them can have its own title.

**Comment by dnoclark** [comment]
Hi Sridhar, same need for me ;)

**Comment by sridharbandi** [comment]
Hi, I wasn't aware that feature is been used. I am working on it and will release it in couple of days.

**Comment by sridharbandi** [comment]
Released V3.0.2 to set Page Title and to get the issues count.
Example: `Issues issues = htmlCsRunner.setPageTile("Page Title").execute();`

**Comment by akramshuja** [comment]
Thank you
